disable sync cron job for now

diff --git a/.github/workflows/sync.yaml b/.github/workflows/sync.yaml
--- a/.github/workflows/sync.yaml
+++ b/.github/workflows/sync.yaml
@@ -1,52 +1,52 @@
-name: sync
-on:
-  push:
-    branches:
-    - main
-  schedule:
-  - cron: "0 */12 * * *"
-  workflow_dispatch:
-env:
-  ITS_IMDB_AUTH: ${{ secrets.IMDB_AUTH }}
-  ITS_IMDB_EMAIL: ${{ secrets.IMDB_EMAIL }}
-  ITS_IMDB_PASSWORD: ${{ secrets.IMDB_PASSWORD }}
-  ITS_IMDB_COOKIEATMAIN: ${{ secrets.IMDB_COOKIEATMAIN }}
-  ITS_IMDB_LISTS: ${{ secrets.IMDB_LISTS }}
-  ITS_IMDB_IGNOREDLISTS: ${{ secrets.IMDB_IGNOREDLISTS }}
-  ITS_IMDB_TRACE: ${{ secrets.IMDB_TRACE }}
-  ITS_IMDB_HEADLESS: true
-  ITS_IMDB_BROWSERPATH: ${{ github.workspace }}/chrome-linux/chrome
-  ITS_SYNC_MODE: ${{ secrets.SYNC_MODE }}
-  ITS_SYNC_HISTORY: ${{ secrets.SYNC_HISTORY }}
-  ITS_SYNC_RATINGS: ${{ secrets.SYNC_RATINGS }}
-  ITS_SYNC_WATCHLIST: ${{ secrets.SYNC_WATCHLIST }}
-  ITS_SYNC_LISTS: ${{ secrets.SYNC_LISTS }}
-  ITS_SYNC_TIMEOUT: ${{ secrets.SYNC_TIMEOUT }}
-  ITS_TRAKT_CLIENTID: ${{ secrets.TRAKT_CLIENTID }}
-  ITS_TRAKT_CLIENTSECRET: ${{ secrets.TRAKT_CLIENTSECRET }}
-  ITS_TRAKT_EMAIL: ${{ secrets.TRAKT_EMAIL }}
-  ITS_TRAKT_PASSWORD: ${{ secrets.TRAKT_PASSWORD }}
-jobs:
-  sync:
-    runs-on: ubuntu-24.04
-    steps:
-    - name: Check out code
-      uses: actions/checkout@v5
-    - name: Install Google Chrome
-      run: |
-        wget -q https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1321438/chrome-linux.zip
-        unzip -q chrome-linux.zip
-        if test -f "$ITS_IMDB_BROWSERPATH"; then
-          echo "Google Chrome binary stored at $ITS_IMDB_BROWSERPATH"
-        else
-          echo "Google Chrome binary not found at $ITS_IMDB_BROWSERPATH"
-          exit 1
-        fi
-    - name: Setup Go
-      uses: actions/setup-go@v6
-      with:
-        go-version: 1.25.1
-    - name: Build
-      run: make build
-    - name: Sync
-      run: make sync
+# name: sync
+# on:
+#   push:
+#     branches:
+#     - main
+#   schedule:
+#   - cron: "0 */12 * * *"
+#   workflow_dispatch:
+# env:
+#   ITS_IMDB_AUTH: ${{ secrets.IMDB_AUTH }}
+#   ITS_IMDB_EMAIL: ${{ secrets.IMDB_EMAIL }}
+#   ITS_IMDB_PASSWORD: ${{ secrets.IMDB_PASSWORD }}
+#   ITS_IMDB_COOKIEATMAIN: ${{ secrets.IMDB_COOKIEATMAIN }}
+#   ITS_IMDB_LISTS: ${{ secrets.IMDB_LISTS }}
+#   ITS_IMDB_IGNOREDLISTS: ${{ secrets.IMDB_IGNOREDLISTS }}
+#   ITS_IMDB_TRACE: ${{ secrets.IMDB_TRACE }}
+#   ITS_IMDB_HEADLESS: true
+#   ITS_IMDB_BROWSERPATH: ${{ github.workspace }}/chrome-linux/chrome
+#   ITS_SYNC_MODE: ${{ secrets.SYNC_MODE }}
+#   ITS_SYNC_HISTORY: ${{ secrets.SYNC_HISTORY }}
+#   ITS_SYNC_RATINGS: ${{ secrets.SYNC_RATINGS }}
+#   ITS_SYNC_WATCHLIST: ${{ secrets.SYNC_WATCHLIST }}
+#   ITS_SYNC_LISTS: ${{ secrets.SYNC_LISTS }}
+#   ITS_SYNC_TIMEOUT: ${{ secrets.SYNC_TIMEOUT }}
+#   ITS_TRAKT_CLIENTID: ${{ secrets.TRAKT_CLIENTID }}
+#   ITS_TRAKT_CLIENTSECRET: ${{ secrets.TRAKT_CLIENTSECRET }}
+#   ITS_TRAKT_EMAIL: ${{ secrets.TRAKT_EMAIL }}
+#   ITS_TRAKT_PASSWORD: ${{ secrets.TRAKT_PASSWORD }}
+# jobs:
+#   sync:
+#     runs-on: ubuntu-24.04
+#     steps:
+#     - name: Check out code
+#       uses: actions/checkout@v5
+#     - name: Install Google Chrome
+#       run: |
+#         wget -q https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1321438/chrome-linux.zip
+#         unzip -q chrome-linux.zip
+#         if test -f "$ITS_IMDB_BROWSERPATH"; then
+#           echo "Google Chrome binary stored at $ITS_IMDB_BROWSERPATH"
+#         else
+#           echo "Google Chrome binary not found at $ITS_IMDB_BROWSERPATH"
+#           exit 1
+#         fi
+#     - name: Setup Go
+#       uses: actions/setup-go@v6
+#       with:
+#         go-version: 1.25.1
+#     - name: Build
+#       run: make build
+#     - name: Sync
+#       run: make sync
